### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by cnnetarmy** [knownsec/Pocsuite#106]
http://pocsuite.org/ 相关链接
Change Log
https://github.com/knownsec/Pocsuite/blob/master/docs/CHANGLOG.md

Issues:
https://github.com/knownsec/Pocsuite/blob/master/docs/CHANGELOG.md

**Comment by nixawk** [comment]
Thanks @cnnetarmy 
![screen shot 2016-07-24 at 23 06 56](https://cloud.githubusercontent.com/assets/7352479/17090137/62888c2e-51f3-11e6-9c7f-e11d84dcf154.png)

**Comment by nixawk** [comment]
@cnnetarmy  Fixed.
