### ISSUE TITLE
url2ip返回类型不一致

### ISSUE THREAD

**Issue by Leocodefocus** [knownsec/Pocsuite#147]
## OS / Software Version

- Linux * 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- 2.0.6

## How to reproduce the issue ?
`
>>> from pocsuite.api.utils import url2ip
>>> from socket import gethostbyname
>>> ipp = url2ip('https://github.com')
>>> ipp
'192.30.253.113'
>>> ipp = url2ip('https://github.com:80')
>>> ipp
('192.30.253.112', 80)
>>> ipp[0]
'192.30.253.112'
>>> ipp = url2ip('https://github.com')
>>> ipp[0]
'1'
>>> 
`
所以这个是不是有必要改一下，固定类型的输入, 固定类型的输出，否则批量处理时url格式不统一，总是判断类型，不如api给做了。
```
def url2ip(url):
    """
    works like turning 'http://baidu.com' => '180.149.132.47'
    """

    urlPrased = urlparse(url)
    if urlPrased.port:
        return gethostbyname(urlPrased.hostname), urlPrased.port
    return gethostbyname(urlPrased.hostname)
```
例如：

```
def url2ip(url):
    """
    works like turning 'http://baidu.com' => '180.149.132.47'
    """
    ipp = urlsplit(url)
    iport = ipp[1].split(':')
    if len(iport) > 1:
        return gethostbyname(iport[0]), iport[1]
    else:
        if 'https' == ipp[0]:
            return gethostbyname(iport[0]),443
        elif 'http' == ipp[0]:
            return gethostbyname(iport[0]),80
    return gethostbyname(iport[0]),0
```

**Comment by hysia** [comment]
api 统一处理，欢迎提交 PR

**Comment by hysia** [comment]
现在可以用 `url2ip('https://domain.com', with_port=True)` 来实现同时获得 IP 和端口，默认还是返回 IP

**Comment by Leocodefocus** [comment]
ok
