### ISSUE TITLE
https://api.zoomeye.org/resources-info 接口返回数据不一致

### ISSUE THREAD

**Issue by alchu4n** [knownsec/Pocsuite#150]
官方api参考手册
cURL 示例

curl -X GET -i https://api.zoomeye.org/resources-info \
-H "Authorization: JWT eyJhbGciOiJIUzI1NiIsInR..."
响应示例

HTTP/1.1 200 OK
Date: Tue, 01 Mar 2016 10:08:09 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 72
Connection: keep-alive
Etag: "f3fdef1e608ffc4b48cd306f068550ff046652c1"
{"plan": "developer", "resources": {"host-search": 9, "web-search": 40}}

我本地测试返回 
HTTP/1.1 200 OK
Server: nginx/1.12.1
Date: Fri, 19 Jan 2018 12:26:32 GMT
Content-Type: application/json
Content-Length: 89
Connection: keep-alive
Etag: "6f6744c5f99466c9278c19b331de61a5272ff939"

{"plan": "developer", "resources": {"search": 100000, "stats": 100, "interval": "month"}}%

与官方文档不一致

**Comment by hysia** [comment]
更新 zoomeye 官方 api 文档处理
