### ISSUE TITLE
add english documents for pocsuite

### ISSUE THREAD

**Issue by fooying** [knownsec/Pocsuite#24]
需要个英文版的帮助文档

**Comment by DarwinniwraD** [comment]
https://help.github.com/categories/github-pages-basics/

**Comment by DarwinniwraD** [comment]
可以参考一下https://help.github.com/categories/github-pages-basics/

**Comment by fooying** [comment]
目前功能介绍已有英文文档，缺少开发手册及使用帮助的英文文档

**Comment by join-us** [comment]
If interesting,  you can add english docs for development / features / anything that you want to show.

**Comment by join-us** [comment]
https://github.com/knownsec/Pocsuite/pull/71 - Add english README / Usage documentation.
