### ISSUE TITLE
框架调用Attack前自动调用Verify功能

### ISSUE THREAD

**Issue by Medicean** [knownsec/Pocsuite#28]
考虑到降低 Attack 方法的误报率，在 Attack 前先调用 Verify，验证存在漏洞后再进行 Attack 逻辑。

* 好处是误报率大大降低,并且降低 Attack 逻辑编写难度

* 缺点是会增加一倍的时间成本。

现在问题来了，要不要框架自动调用 Verify?

**Comment by Wyc0** [comment]
不要啊 这个跟马健之前讨论过了

**Comment by Wyc0** [comment]
不要啊 这个之前跟flsf讨论过了
