### ISSUE TITLE
Is it necessary to put third-party modules  in the [thirdparty direcroty]

### ISSUE THREAD

**Issue by fooying** [knownsec/Pocsuite#75]
Is it necessary to put third-party modules  in the [thirdparty direcroty](https://github.com/knownsec/Pocsuite/tree/dev/pocsuite/thirdparty)?

Benefit：
* It's so simple to use **Pocsuite**.  Download and extract the source code.
* For beginners, it is easy to get started.

Disadvantage：
* Modules may use python libraries which are not installed by **Pocsuite**.
* Hard to provide cross-platform support 
* Performance is limited. ex: gevent VS thread 

----

**讨论下关于第三方模块引用的问题**

是否有必要编译封装第三方模块在「thirdparty」目录

好处：
* 直接下载源码就可以使用Pocsuite，而不需要安装，简单易用
* 对于新手来说比较容易上手

坏处：
* 编译封装的第三方模块在不同平台可能会出现问题
* 类似于gevent等只能（不同平台下的编译不同）通过pip install 安装的第三方模块就没法使用，于是Pocsuite就没法使用协程来提供性能

看起来似乎是否可以维护两个分支？

一个是当前代码版本，能提供基本的调用功能即可，主要面向于新手，一些不会安装的用户。

一个新版本，采用协程提高性能，通过Makefile 等方式让使用者以安装的形式安装Pocsuite及依赖的模块，这个版本为以后主要开发版本

**Comment by join-us** [comment]
@fooying I've created a project called [**AsyncWorker**](https://github.com/open-security/AsyncWorker) to make asynchronous tasks easily..

**Comment by MyKings** [comment]
@fooying 

**Two approaches:**

* Integration of third-party packages, providing different platforms pocsuite program. 
> e.g. pocsuite-linux, pocsuite-win, pocsuite-mac

* Use setuptools management depends.


I think it can be two parallel.

The first, stable version, each release version of a long time. Mainly to solve different platform stability.

The second, development version will be updated in real time, but may not be stable.
