### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by inno-jeremy** [knownsec/Pocsuite#85]
https://github.com/knownsec/Pocsuite/blob/master/docs/CODING.md
”为了防止误报产生以及避免被关键词被WAF等作为检测特征,要求验证结果判断的时候输出随机的字符串（可以调用API中的randoStr方法）“中的“randoStr”应为“randomStr”。

**Comment by Wyc0** [comment]
直接提交pull request啊少年

**Comment by join-us** [comment]
@inno-jeremy Thanks. I'll fix it.
